version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: data-access-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
